"""Bead loop generator.

A bead generator creates a decorative groove/bead along domain boundaries.
Unlike profile cuts which separate parts, beads are decorative features
that stay within the material, creating visual emphasis around edges or
holes.

Beads are generated by insetting/offsetting the domain boundary and
creating an engrave path along the offset line.

Usage:
    from domains import Domain
    from generators.loop.bead import bead_generator
    from generators.base import BeadParams

    domain = Domain.from_rectangle(100, 100, center=(50, 50))
    params = BeadParams(width_mm=6.0, depth_mm=3.0, offset_mm=10.0)
    items = bead_generator(domain, params)

    # Items can then be added to a LayoutAST
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from generators.base import (
    BeadParams,
    GeneratorResult,
    LoopSelection,
    generate_shape_id,
    validate_domain_for_generation,
)
from layout_ast.layout import Feature, Geometry, Item, Placement

if TYPE_CHECKING:
    from domains import Domain


def _extract_loops(
    domain: Domain,
    selection: LoopSelection,
) -> list[tuple[int, tuple[tuple[float, float], ...]]]:
    """Extract loops from domain based on selection.

    This is similar to the loop extraction in profile.py but duplicated
    here to keep the bead generator self-contained.

    Args:
        domain: The domain to extract loops from
        selection: Which loops to extract

    Returns:
        List of (index, boundary_points) tuples

    Raises:
        ValueError: If selection references invalid loop indices
    """
    all_loops = [domain.outer_boundary] + list(domain.inner_boundaries)
    num_loops = len(all_loops)

    if selection == "outer_only":
        return [(0, domain.outer_boundary)]

    elif selection == "inner_only":
        return [
            (i + 1, inner)
            for i, inner in enumerate(domain.inner_boundaries)
        ]

    elif selection == "all_loops":
        return [(i, loop) for i, loop in enumerate(all_loops)]

    elif isinstance(selection, list):
        result = []
        for idx in selection:
            if idx < 0 or idx >= num_loops:
                raise ValueError(
                    f"BeadGenerator: loop index {idx} out of range. "
                    f"Domain has {num_loops} loops (0=outer, 1-{num_loops-1}=inner)"
                )
            result.append((idx, all_loops[idx]))
        return result

    else:
        raise ValueError(f"BeadGenerator: invalid loop_selection: {selection}")


def _loop_type_suffix(index: int) -> str:
    """Generate suffix for shape ID based on loop index."""
    if index == 0:
        return "outer"
    return f"inner_{index}"


def _offset_boundary(
    boundary: tuple[tuple[float, float], ...],
    offset: float,
    is_outer: bool,
) -> tuple[tuple[float, float], ...] | None:
    """Offset a boundary inward or outward.

    For outer boundaries, positive offset moves inward.
    For inner boundaries (holes), positive offset moves outward (away from hole center).

    Args:
        boundary: The boundary points to offset
        offset: Offset distance in mm
        is_outer: True if this is the outer boundary

    Returns:
        Offset boundary points, or None if offset collapses the boundary
    """
    if offset == 0:
        return boundary

    from shapely.geometry import Polygon
    from shapely.ops import orient

    # Create polygon from boundary
    poly = Polygon(boundary)

    # For outer boundary, inward offset is negative buffer
    # For inner boundary, we want to move outward from the hole, which is positive buffer
    buffer_distance = -offset if is_outer else offset

    result = poly.buffer(buffer_distance, join_style=2)  # mitre join

    if result.is_empty or result.area < 0.01:
        return None

    # Ensure correct winding
    result = orient(result, sign=1.0)

    # Extract coordinates
    if result.geom_type == "Polygon":
        coords = list(result.exterior.coords)[:-1]  # Remove closing point
        return tuple((float(x), float(y)) for x, y in coords)

    # If buffer created multiple polygons, take the largest
    if result.geom_type == "MultiPolygon":
        largest = max(result.geoms, key=lambda g: g.area)
        coords = list(largest.exterior.coords)[:-1]
        return tuple((float(x), float(y)) for x, y in coords)

    return None


def bead_generator(
    domain: Domain,
    params: BeadParams,
    *,
    allow_empty: bool = False,
    shape_id_prefix: str = "bead",
) -> GeneratorResult:
    """Generate bead/groove items along domain boundaries.

    Creates Polygon items with engrave features that follow the specified
    loops of the domain at an offset distance. Each selected loop produces
    one Item representing a decorative groove.

    Args:
        domain: The domain defining the bead region
        params: Bead parameters (width, depth, offset, loop selection)
        allow_empty: If True, return empty list instead of raising when
            the domain has no matching loops or offset is too large
        shape_id_prefix: Prefix for generated shape IDs

    Returns:
        List of Polygon Items with engrave features, one per selected loop

    Raises:
        ValueError: If params are invalid or requested loops don't exist
            (unless allow_empty)

    Example:
        >>> domain = Domain.from_rectangle(100, 50, center=(50, 25))
        >>> params = BeadParams(width_mm=6.0, depth_mm=3.0, offset_mm=10.0)
        >>> items = bead_generator(domain, params)
        >>> len(items)
        1
        >>> items[0].feature.type
        'engrave'
    """
    # Validate parameters
    params.validate()

    # Validate domain
    if not validate_domain_for_generation(
        domain,
        min_area_mm2=0.01,
        allow_empty=allow_empty,
        generator_name="BeadGenerator",
    ):
        return []

    # Extract the loops to process
    try:
        loops = _extract_loops(domain, params.loop_selection)
    except ValueError:
        if allow_empty:
            return []
        raise

    if not loops:
        if allow_empty:
            return []
        raise ValueError(
            f"BeadGenerator: No loops match selection '{params.loop_selection}'"
        )

    items: list[Item] = []

    for loop_idx, boundary in loops:
        is_outer = (loop_idx == 0)

        # Offset the boundary
        offset_boundary = _offset_boundary(
            boundary,
            params.offset_mm,
            is_outer,
        )

        if offset_boundary is None:
            if allow_empty:
                continue
            raise ValueError(
                f"BeadGenerator: offset {params.offset_mm}mm collapses loop {loop_idx}. "
                f"Use a smaller offset value."
            )

        # Build polygon geometry from offset boundary points
        polygon_points = [list(pt) for pt in offset_boundary]

        geometry_data = {
            "points": polygon_points,
            "width_mm": params.width_mm,  # Tool width for path planning
        }

        # Compute center for placement (centroid of the offset boundary)
        cx = sum(p[0] for p in offset_boundary) / len(offset_boundary)
        cy = sum(p[1] for p in offset_boundary) / len(offset_boundary)

        # Create the Item
        item = Item(
            kind="shape",
            type="Polygon",
            geometry=Geometry(data=geometry_data),
            placement=Placement(center_xy_mm=(cx, cy)),
            feature=Feature(
                type="engrave",
                depth=str(params.depth_mm),
                depth_mm=params.depth_mm,
            ),
            shape_id=generate_shape_id(
                shape_id_prefix,
                loop_idx,
                _loop_type_suffix(loop_idx),
            ),
        )

        items.append(item)

    if not items and not allow_empty:
        raise ValueError(
            f"BeadGenerator: Could not generate any bead items. "
            f"Check offset parameter and domain size."
        )

    return items


__all__ = ["bead_generator"]
