coarse:
  tool_diameter: 6.35
  stepover: 3.0
  z_scale: 3.0
  z_clamp: [-2.8, 0.0]
  z_buffer: 0.5
  tool_type: flat
  max_feedrate: 500

fine:
  tool_diameter: 3.175
  stepover: 0.4
  z_scale: 3.0
  tool_type: ball
  z_clamp: [-3.0, -0.0]
  z_smooth_kernel: 5
  max_feedrate: 900
