from assembly.core import (
    Assembly,
    EdgeName,
    Interface,
    InterfaceType,
    MemberSpec,
    RemovalKind,
)
from assembly.panel import (
    DadoSpec,
    Edge,
    NotchSpec,
    PanelRole,
    PanelSpec,
    validate_notch_fits_edge,
    validate_notches_no_overlap,
)
from assembly.joinery import (
    Butt,
    Captured,
    Finger,
    HalfLap,
    JoineryStrategy,
)
from assembly.primitives import (
    box,
    carcass,
    cubby,
)
from assembly.layout import (
    LayoutConfig,
    PlacedPanel,
    layout_panels,
    panels_to_layout_ast,
)

from assembly.notches import (
    NotchSpec as LegacyNotchSpec,
    build_notched_polygon,
    finger_joints_to_notches,
    notch_to_polyline,
    validate_notch_fits_edge as legacy_validate_notch_fits_edge,
    validate_notches_no_overlap as legacy_validate_notches_no_overlap,
)
from assembly.beam import (
    BeamSpec,
    BeamRole,
    LayerSpec,
    Cutout,
    Segment,
    MachiningStage,
    DrillHole,
    SquareMortise,
    CarvedDesign,
    GeometricPattern,
    FaceFeature,
    Tenon,
    EndCap,
    EndProfile,
    EndFeature,
    Fillet,
    Chamfer,
    Rabbet,
    EdgeDado,
    EdgeNotch,
    EdgeContour,
    EdgeFeature,
    compute_segments,
    validate_butts_never_align,
    validate_stagger_minimum,
)
from assembly.beam_primitives import (
    post,
    rail,
    leg,
    apron,
    chamfered_post,
    filleted_leg,
)

__all__ = [
    "Assembly",
    "EdgeName",
    "Interface",
    "InterfaceType",
    "MemberSpec",
    "RemovalKind",
    "DadoSpec",
    "Edge",
    "NotchSpec",
    "PanelRole",
    "PanelSpec",
    "validate_notch_fits_edge",
    "validate_notches_no_overlap",
    "Butt",
    "Captured",
    "Finger",
    "HalfLap",
    "JoineryStrategy",
    "box",
    "carcass",
    "cubby",
    "LayoutConfig",
    "PlacedPanel",
    "layout_panels",
    "panels_to_layout_ast",
    "LegacyNotchSpec",
    "build_notched_polygon",
    "finger_joints_to_notches",
    "notch_to_polyline",
    "BeamSpec",
    "BeamRole",
    "LayerSpec",
    "Cutout",
    "Segment",
    "MachiningStage",
    "DrillHole",
    "SquareMortise",
    "CarvedDesign",
    "GeometricPattern",
    "FaceFeature",
    "Tenon",
    "EndCap",
    "EndProfile",
    "EndFeature",
    "Fillet",
    "Chamfer",
    "Rabbet",
    "EdgeDado",
    "EdgeNotch",
    "EdgeContour",
    "EdgeFeature",
    "compute_segments",
    "validate_butts_never_align",
    "validate_stagger_minimum",
    "post",
    "rail",
    "leg",
    "apron",
    "chamfered_post",
    "filleted_leg",
]
